### Register a new user
POST http://localhost:3333/register
Content-Type: application/json

{
  "name": "Test User",
  "email": "test@example.com",
  "password": "Test@123!"
}

### Login
POST http://localhost:3333/login
Content-Type: application/json

{
  "email": "test@example.com",
  "password": "Test@123!"
}

### Save the accessToken and refreshToken from the response




### Create News (Protected Route)
POST http://localhost:3333/news
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwMmQzZjZiMS0yMTliLTQzN2YtOTM4My0yNDRiZTA2MTZjODEiLCJlbWFpbCI6InRlc3RAZXhhbXBsZS5jb20iLCJpYXQiOjE3MzA0MDA0NTksImV4cCI6MTczMDQwMTM1OX0.G-pBq2Fy2nPRHFfyPEw_wanUT6QeCGhW2Ck7ayisyR4

{
  "title": "Test News 3",
  "body": "This is a test news article",
  "author": "Test Author",
  "imageUrl": "https://example.com/image.jpg"
}



### List All News (Public Route)
GET http://localhost:3333/news

### Get Single News (Public Route)
GET http://localhost:3333/news/3c310120-f74f-4b78-b84b-9670745db3f6




### Update News (Protected Route)
PUT http://localhost:3333/news/3c310120-f74f-4b78-b84b-9670745db3f6
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwMmQzZjZiMS0yMTliLTQzN2YtOTM4My0yNDRiZTA2MTZjODEiLCJlbWFpbCI6InRlc3RAZXhhbXBsZS5jb20iLCJpYXQiOjE3MzA0MDA0NTksImV4cCI6MTczMDQwMTM1OX0.G-pBq2Fy2nPRHFfyPEw_wanUT6QeCGhW2Ck7ayisyR4

{
  "title": "Updated Title",
  "body": "Updated content"
}

### Delete News (Protected Route)
DELETE http://localhost:3333/news/3c310120-f74f-4b78-b84b-9670745db3f6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwMmQzZjZiMS0yMTliLTQzN2YtOTM4My0yNDRiZTA2MTZjODEiLCJlbWFpbCI6InRlc3RAZXhhbXBsZS5jb20iLCJpYXQiOjE3MzA0MDA0NTksImV4cCI6MTczMDQwMTM1OX0.G-pBq2Fy2nPRHFfyPEw_wanUT6QeCGhW2Ck7ayisyR4

### Generate Presigned URL (Protected Route)
POST http://localhost:3333/presigned-url
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwMmQzZjZiMS0yMTliLTQzN2YtOTM4My0yNDRiZTA2MTZjODEiLCJlbWFpbCI6InRlc3RAZXhhbXBsZS5jb20iLCJpYXQiOjE3MzA2NDgyNTMsImV4cCI6MTczMDY0OTE1M30.g-BBdcF1ly2Bna1b8_OXnMaqoyNvxGDXXXSHRqRhxZo 

{
  "fileName": "test-image.jpg",
  "fileSize": 1048576,
  "contentType": "image/jpeg"
}

